### ISSUE TITLE
The recipe for distcc cannot be build on R2018.2.

### ISSUE THREAD

**Issue by Brainiarc7** [Xilinx/meta-petalinux#6]
Hello there,

I'm hoping that this is the correct place for this issue.
Earlier on, I tried building a yocto recipe for the ZCU106 based on this layer, and it failed at building distcc as shown:

```
| In file included from /usr/include/python2.7/Python.h:8:0,
|                  from /home/brainiarc7/source.build/zcu106/build/tmp/work/aarch64-xilinx-linux/distcc/3.2-maint-r0/git/include_server/c_extensions/distcc_pump_c_extensions_module.c:24:
| /usr/include/python2.7/pyconfig.h:12:12: fatal error: aarch64-linux-gnu/python2.7/pyconfig.h: No such file or directory
|  #  include <aarch64-linux-gnu/python2.7/pyconfig.h>
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| error: command 'aarch64-xilinx-linux-gcc' failed with exit status 1
| Makefile:570: recipe for target 'include-server' failed
| make: *** [include-server] Error 1
| ERROR: oe_runmake failed
```

On the host system, all python related dependencies, ie python-dev, are installed.

How can I fix this error?

Thanks.

**Comment by ifgoto** [comment]
same error,,need help

**Comment by mharth** [comment]
Do you still have this issue in latest release?

**Comment by Brainiarc7** [comment]
@mharth I'll retest and report back.
